global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'summit-fabric'
    static_configs:
      - targets: ['fabric:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'summit-fusion'
    static_configs:
      - targets: ['fusion:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'summit-intelligence'
    static_configs:
      - targets: ['intelligence:8003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'summit-tasking'
    static_configs:
      - targets: ['tasking:8004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'summit-api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
