apiVersion: apps/v1
kind: Deployment
metadata:
  name: summit-fusion
  labels:
    app: summit-fusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summit-fusion
  template:
    metadata:
      labels:
        app: summit-fusion
    spec:
      containers:
        - name: fusion
          image: ghcr.io/bigmt/summit-fusion:latest
          ports:
            - containerPort: 8002
          env:
            - name: REDIS_URL
              value: redis://summit-redis:6379
            - name: POSTGRES_URL
              value: postgresql://summit:summit_password@summit-postgres:5432/summit_os
---
apiVersion: v1
kind: Service
metadata:
  name: summit-fusion
spec:
  selector:
    app: summit-fusion
  ports:
    - name: http
      port: 8002
      targetPort: 8002
