apiVersion: apps/v1
kind: Deployment
metadata:
  name: summit-tasking
  labels:
    app: summit-tasking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summit-tasking
  template:
    metadata:
      labels:
        app: summit-tasking
    spec:
      containers:
        - name: tasking
          image: ghcr.io/bigmt/summit-tasking:latest
          ports:
            - containerPort: 8004
          env:
            - name: REDIS_URL
              value: redis://summit-redis:6379
            - name: POSTGRES_URL
              value: postgresql://summit:summit_password@summit-postgres:5432/summit_os
---
apiVersion: v1
kind: Service
metadata:
  name: summit-tasking
spec:
  selector:
    app: summit-tasking
  ports:
    - name: http
      port: 8004
      targetPort: 8004
