name: contract-tests-template
on:
  push:
    paths:
      - 'docs/platform/schemas/**'
      - 'docs/platform/examples/**'
      - 'ci/templates/**'
  pull_request:
    paths:
      - 'docs/platform/schemas/**'
      - 'docs/platform/examples/**'
      - 'ci/templates/**'

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ci/templates/requirements.txt
      - name: Run contract tests (schemas/examples)
        run: pytest ci/templates/contract_test_template.py -q
      - name: Optional live API validation
        if: ${{ env.API_BASE_URL != '' }}
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: pytest ci/templates/contract_test_template.py -q
